# Generated by Django 3.2.3 on 2021-06-05 20:32

import autoslug.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите ингредиент', max_length=100, verbose_name='Ингредиент')),
                ('dimension', models.CharField(help_text='В чём измеряется', max_length=15, verbose_name='Измерение')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Введите количество ингредиента', verbose_name='Количество ингредиента')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название рецепта', max_length=50, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(help_text='Введите описание рецепта', verbose_name='Описание рецепта')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='Краткий url рецепта', populate_from='title', unique=True, verbose_name='Слаг рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Введите время приготовления в минутах', verbose_name='Время приготовления')),
                ('image', models.ImageField(blank=True, default='testCardImg.png', help_text='Вы можете прикрепить к своему рецепту картинку', null=True, upload_to='recipes/', verbose_name='Картинка рецепта')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название тега', max_length=20, verbose_name='Тег')),
                ('tag', models.CharField(help_text='Введите значение тега', max_length=20, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='Выберите рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='shoplists', to='Recipes.recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
