# Generated by Django 3.2.3 on 2021-05-29 12:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Введите описание рецепта', verbose_name='Описание рецепта'),
        ),
    ]
